printWidth: 80
tabWidth: 2
useTabs: false
semi: false
singleQuote: true
trailingComma: none
bracketSpacing: true
jsxBracketSameLine: false
arrowParens: avoid
plugins: ['prettier-plugin-astro']
overrides: [{ files: '*.astro', options: { parser: 'astro' } }]
astroAllowShorthand: true
